# Generated by Django 4.1.2 on 2022-10-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('contenido', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=40)),
            ],
        ),
    ]
