# Generated by Django 4.1.2 on 2022-10-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogDeCafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupos',
            field=models.IntegerField(default=20),
        ),
    ]
