# Generated by Django 4.1.2 on 2022-10-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogDeCafe', '0002_curso_cupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
