# Generated by Django 4.1.2 on 2022-10-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogDeCafe', '0003_alter_entrada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
